imports:
  - { resource: "EXT:rte_ckeditor/Configuration/RTE/Minimal.yaml" }

editor:
  config:
    importModules:
      - { module: '@nkfire/rescue-reports/text-snippets-1.0.20.js', exports: [ 'TextSnippets' ] }

    toolbar:
      items:
        - style
        - heading
        - '|'
        - bold
        - italic
        - subscript
        - superscript
        - '|'
        - bulletedList
        - numberedList
        - blockQuote
        - link
        - '|'
        - textsnippets
        - removeFormat
        - undo
        - redo
        - sourceEditing

    contentsCss:
      - "EXT:rte_ckeditor/Resources/Public/Css/contents.css"
      - "EXT:rescue_reports/Resources/Public/Css/rte.css"
