services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  nkfire\RescueReports\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Domain/Model/*'
      - '../Classes/Domain/Repository/*'

  # Repositories: enabled autowiring for DI since controllers inject them via constructor
  nkfire\RescueReports\Domain\Repository\:
    resource: '../Classes/Domain/Repository/*'
    autoconfigure: true
    autowire: true

  nkfire\RescueReports\Updates\InitialDataWizard:
    tags:
      - name: install.upgradewizard

  nkfire\RescueReports\EventListener\DataHandlerEventListener:
    tags:
      - name: event.listener
        event: 'TYPO3\CMS\Core\DataHandling\Event\BeforeRecordCreatedEvent'
        method: beforeRecordCreated
      - name: event.listener
        event: 'TYPO3\CMS\Core\DataHandling\Event\BeforeRecordUpdatedEvent'
        method: beforeRecordUpdated

  nkfire\RescueReports\Routing\StationPrefixAspect:
    public: true
    tags:
      - name: routing.aspect
