services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  nkfire\RescueReports\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Domain/Model/*'

  nkfire\RescueReports\Updates\InitialDataWizard:
    tags:
      - name: install.upgradewizard

  nkfire\RescueReports\EventListener\VehicleNameAutoFillListener:
    tags:
      - name: event.listener
        event: 'TYPO3\CMS\Core\DataHandling\Event\AfterRecordCreatedEvent'

  nkfire\RescueReports\EventListener\DataHandlerEventListener:
    tags:
      - name: event.listener
        event: 'TYPO3\CMS\Core\DataHandling\Event\BeforeRecordCreatedEvent'
      - name: event.listener
        event: 'TYPO3\CMS\Core\DataHandling\Event\BeforeRecordUpdatedEvent'
